query ProjectDetails($projectId: ID!) {
    node(id: $projectId) {
        ... on ProjectV2 {
            id
            title
            shortDescription
            url
            number
            createdAt
            closed
            fields(first: 50) {
                nodes {
                    ... on ProjectV2Field {
                        id
                        name
                        dataType
                    }
                    ... on ProjectV2IterationField {
                        id
                        name
                        dataType
                        configuration {
                            iterations {
                                startDate
                                duration
                            }
                        }
                    }
                    ... on ProjectV2SingleSelectField {
                        id
                        name
                        dataType
                        options {
                            id
                            name
                            color
                        }
                    }
                }
            }
            items(first: 100) {
                nodes {
                    id
                    type
                    content {
                        ... on Issue {
                            id
                            title
                            number
                            state
                            createdAt
                            updatedAt
                            author {
                                login
                                avatarUrl
                            }
                            body
                            url
                            repository {
                                name
                                owner {
                                    login
                                }
                            }
                            labels(first: 10) {
                                nodes {
                                    name
                                    color
                                }
                            }
                            assignees(first: 5) {
                                nodes {
                                    login
                                    avatarUrl
                                }
                            }
                        }
                        ... on PullRequest {
                            id
                            title
                            number
                            # state
                            createdAt
                            updatedAt
                            author {
                                login
                                avatarUrl
                            }
                            body
                            url
                            repository {
                                name
                                owner {
                                    login
                                }
                            }
                            labels(first: 10) {
                                nodes {
                                    name
                                    color
                                }
                            }
                            assignees(first: 5) {
                                nodes {
                                    login
                                    avatarUrl
                                }
                            }
                        }
                    }
                    fieldValues(first: 50) {
                        nodes {
                            ... on ProjectV2ItemFieldTextValue {
                                text
                                field {
                                    ... on ProjectV2Field {
                                        id
                                        name
                                    }
                                }
                            }
                            ... on ProjectV2ItemFieldDateValue {
                                date
                                field {
                                    ... on ProjectV2Field {
                                        id
                                        name
                                    }
                                }
                            }
                            ... on ProjectV2ItemFieldIterationValue {
                                iterationId
                                title
                                startDate
                                duration
                                field {
                                    ... on ProjectV2IterationField {
                                        id
                                        name
                                    }
                                }
                            }
                            ... on ProjectV2ItemFieldNumberValue {
                                number
                                field {
                                    ... on ProjectV2Field {
                                        id
                                        name
                                    }
                                }
                            }
                            ... on ProjectV2ItemFieldSingleSelectValue {
                                name
                                field {
                                    ... on ProjectV2SingleSelectField {
                                        id
                                        name
                                    }
                                }
                            }
                        }
                    }
                }
                pageInfo {
                    hasNextPage
                    endCursor
                }
            }
        }
    }
}
